// packages/react/src/context.tsx
import {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback,
  useRef,
  useMemo,
  type ReactNode,
} from "react";
import { OidcClient, type OidcClientConfig, type AuthState, type LoginOptions } from "oidc-js";
import type { AuthContextValue } from "./types.js";

const AuthContext = createContext<AuthContextValue | null>(null);

interface AuthProviderProps {
  config: OidcClientConfig;
  fetchProfile?: boolean;
  onLogin?: (returnTo: string) => void;
  onError?: (error: Error) => void;
  children: ReactNode;
}

export function AuthProvider({
  config,
  fetchProfile = true,
  onLogin,
  onError,
  children,
}: AuthProviderProps) {
  const clientRef = useRef<OidcClient | null>(null);
  const [state, setState] = useState<AuthState>(() => ({
    user: null,
    isAuthenticated: false,
    isLoading: true,
    error: null,
    tokens: { access: null, id: null, refresh: null, expiresAt: null },
  }));

  const onLoginRef = useRef(onLogin);
  onLoginRef.current = onLogin;

  const onErrorRef = useRef(onError);
  onErrorRef.current = onError;

  useEffect(() => {
    const client = new OidcClient({ ...config, fetchProfile });
    clientRef.current = client;

    const unsub = client.subscribe(setState);

    client.init().then(({ returnTo }) => {
      const s = client.state;
      if (s.error) onErrorRef.current?.(s.error);
      if (returnTo) {
        if (onLoginRef.current) {
          onLoginRef.current(returnTo);
        } else {
          window.history.replaceState({}, "", returnTo);
        }
      }
    });

    return () => {
      unsub();
      client.destroy();
    };
  }, [config, fetchProfile]);

  const login = useCallback(
    async (options?: LoginOptions) => {
      await clientRef.current?.login(options);
    },
    [],
  );

  const logout = useCallback(() => {
    clientRef.current?.logout();
  }, []);

  const refresh = useCallback(async () => {
    const result = await clientRef.current?.refresh();
    return result ?? { access: null, id: null, refresh: null, expiresAt: null };
  }, []);

  const doFetchProfile = useCallback(async () => {
    return (await clientRef.current?.fetchProfile()) ?? null;
  }, []);

  const actions = useMemo(
    () => ({ login, logout, refresh, fetchProfile: doFetchProfile }),
    [login, logout, refresh, doFetchProfile],
  );

  const value: AuthContextValue = useMemo(
    () => ({ config, client: clientRef.current!, ...state, actions }),
    [config, state, actions],
  );

  return <AuthContext value={value}>{children}</AuthContext>;
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
}

// packages/solid/src/context.tsx
import {
  createContext,
  useContext,
  createSignal,
  onMount,
  onCleanup,
  type ParentComponent,
} from "solid-js";
import { OidcClient, type OidcClientConfig, type AuthState, type LoginOptions } from "oidc-js";
import type { AuthContextValue } from "./types.js";

const AuthContext = createContext<AuthContextValue>();

/**
 * Props for the {@link AuthProvider} component.
 */
interface AuthProviderProps {
  /** OIDC configuration including issuer, clientId, and redirectUri. */
  config: OidcClientConfig;
  /** Callback invoked after a successful login with the returnTo path. */
  onLogin?: (returnTo: string) => void;
  /** Callback invoked when an authentication error occurs. */
  onError?: (error: Error) => void;
}

const INITIAL_STATE: AuthState = {
  user: null,
  isAuthenticated: false,
  isLoading: true,
  error: null,
  tokens: { access: null, id: null, refresh: null, expiresAt: null },
};

/**
 * SolidJS context provider that manages OIDC authentication state.
 *
 * Creates an {@link OidcClient} instance, initializes it on mount,
 * subscribes to state changes via signals, and cleans up on unmount.
 *
 * @example
 * ```tsx
 * <AuthProvider config={config} onLogin={(returnTo) => navigate(returnTo, { replace: true })}>
 *   <App />
 * </AuthProvider>
 * ```
 */
export const AuthProvider: ParentComponent<AuthProviderProps> = (props) => {
  const [state, setState] = createSignal<AuthState>(INITIAL_STATE);

  let client: OidcClient | null = null;

  onMount(() => {
    const oidcClient = new OidcClient(props.config);
    client = oidcClient;

    const unsub = oidcClient.subscribe((newState) => {
      setState(newState);
    });

    oidcClient.init().then(({ returnTo }) => {
      const s = oidcClient.state;
      if (s.error) props.onError?.(s.error);
      if (returnTo) {
        if (props.onLogin) {
          props.onLogin(returnTo);
        } else {
          window.history.replaceState({}, "", returnTo);
        }
      }
    });

    onCleanup(() => {
      unsub();
      oidcClient.destroy();
    });
  });

  const login = async (options?: LoginOptions) => {
    await client?.login(options);
  };

  const logout = () => {
    client?.logout();
  };

  const refresh = async () => {
    const result = await client?.refresh();
    return result ?? { access: null, id: null, refresh: null, expiresAt: null };
  };

  const doFetchProfile = async () => {
    return (await client?.fetchProfile()) ?? null;
  };

  const actions = { login, logout, refresh, fetchProfile: doFetchProfile };

  const value: AuthContextValue = {
    get config() {
      return props.config;
    },
    get user() {
      return state().user;
    },
    get isAuthenticated() {
      return state().isAuthenticated;
    },
    get isLoading() {
      return state().isLoading;
    },
    get error() {
      return state().error;
    },
    get tokens() {
      return state().tokens;
    },
    actions,
  };

  return <AuthContext.Provider value={value}>{props.children}</AuthContext.Provider>;
};

/**
 * SolidJS accessor hook that returns the current authentication context.
 *
 * Must be called within an {@link AuthProvider}. Returns an object with
 * reactive getter properties backed by signals.
 *
 * @returns The current {@link AuthContextValue}.
 * @throws Error if called outside of an AuthProvider.
 *
 * @example
 * ```tsx
 * function Profile() {
 *   const auth = useAuth();
 *   return <div>{auth.user?.claims.sub}</div>;
 * }
 * ```
 */
export function useAuth(): AuthContextValue {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
}
