// packages/solid/src/auth-required.tsx
import { Show, createEffect, type JSX, type ParentComponent } from "solid-js";
import { useAuth } from "./context.js";
import type { LoginOptions } from "oidc-js";
import { isExpiredAt } from "oidc-js-core";

/**
 * Props for the {@link RequireAuth} component.
 */
interface RequireAuthProps {
  /** Content to display while loading or when not authenticated. */
  fallback?: JSX.Element;
  /** Whether to automatically refresh an expired token before redirecting to login. Defaults to true. */
  autoRefresh?: boolean;
  /** Additional options passed to the login redirect. */
  loginOptions?: LoginOptions;
}

/**
 * SolidJS component guard that only renders children when the user is authenticated.
 *
 * If the user's access token is expired, it attempts a silent refresh first.
 * If the refresh fails (or no refresh token exists), it redirects to the login page.
 *
 * @example
 * ```tsx
 * <RequireAuth fallback={<div>Loading...</div>}>
 *   <ProtectedContent />
 * </RequireAuth>
 * ```
 */
export const RequireAuth: ParentComponent<RequireAuthProps> = (props) => {
  const auth = useAuth();
  let refreshAttempted = false;

  createEffect(() => {
    const isExpired = isExpiredAt(auth.tokens.expiresAt, auth.config.expiryBuffer);
    const needsAuth = !auth.isAuthenticated || isExpired;

    if (!needsAuth) {
      refreshAttempted = false;
      return;
    }
    if (auth.isLoading) return;

    const autoRefresh = props.autoRefresh ?? true;

    if (autoRefresh && !refreshAttempted) {
      refreshAttempted = true;
      auth.actions.refresh().catch(() => auth.actions.login(props.loginOptions));
      return;
    }

    auth.actions.login(props.loginOptions);
  });

  return (
    <Show
      when={!auth.isLoading && auth.isAuthenticated && !isExpiredAt(auth.tokens.expiresAt, auth.config.expiryBuffer)}
      fallback={props.fallback}
    >
      {props.children}
    </Show>
  );
};

// packages/preact/src/auth-required.tsx
import { useEffect, useRef } from "preact/hooks";
import type { ComponentChildren } from "preact";
import { useAuth } from "./context.js";
import type { LoginOptions } from "oidc-js";
import { isExpiredAt } from "oidc-js-core";

interface RequireAuthProps {
  children: ComponentChildren;
  fallback?: ComponentChildren;
  autoRefresh?: boolean;
  loginOptions?: LoginOptions;
}

/**
 * Auth guard component that protects its children behind authentication.
 *
 * If the user is not authenticated, it attempts a silent token refresh (when `autoRefresh`
 * is enabled and a refresh token exists). If refresh fails or is disabled, it redirects
 * to the login page. While loading or refreshing, it renders the optional `fallback`.
 *
 * @param props - Guard configuration including children, fallback UI, and login options.
 */
export function RequireAuth({
  children,
  fallback = null,
  autoRefresh = true,
  loginOptions,
}: RequireAuthProps) {
  const { isAuthenticated, isLoading, tokens, actions, config } = useAuth();
  const refreshAttempted = useRef(false);

  const isExpired = isExpiredAt(tokens.expiresAt, config.expiryBuffer);
  const needsAuth = !isAuthenticated || isExpired;

  useEffect(() => {
    if (!needsAuth) {
      refreshAttempted.current = false;
      return;
    }
    if (isLoading) return;

    if (autoRefresh && !refreshAttempted.current) {
      refreshAttempted.current = true;
      actions.refresh().catch(() => actions.login(loginOptions));
      return;
    }

    actions.login(loginOptions);
  }, [isLoading, needsAuth, autoRefresh, actions, loginOptions]);

  if (isLoading || needsAuth) {
    return fallback;
  }

  return children;
}
